version: 0.0
  os: linux
  files:
  - source: ./
  destination: /home/ec2-user/test
  hooks:
  BeforeInstall:
  - location: scripts/before.sh
  timeout: 300
  runas: root
  AfterInstall:
  - location: scripts/after.sh
  timeout: 300
  runas: root