version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/prefix_define.sh
    - location: scripts/build_library_install.sh
    - location: scripts/Python3_6_install.sh
    - location: scripts/virtualenv_install.sh
